packages:
  - apps/*
  - packages/*
catalog:
  "@commitlint/config-conventional": "^19.8.0"
  "@eslint/compat": "^1.2.7"
  "@eslint/js": "^9.22.0"
  "@floating-ui/dom": "^1.6.13"
  "@fontsource/fira-mono": "^5.2.5"
  "@rollup/plugin-commonjs": "^28.0.3"
  "@rollup/plugin-node-resolve": "^16.0.0"
  "@rollup/plugin-typescript": "^12.1.2"
  "@storybook/addon-essentials": "^8.6.4"
  "@storybook/addon-interactions": "^8.6.4"
  "@storybook/addon-links": "^8.6.4"
  "@storybook/addon-svelte-csf": "^4.2.0"
  "@storybook/blocks": "^8.6.4"
  "@storybook/svelte-vite": "^8.6.4"
  "@storybook/svelte": "^8.6.4"
  "@storybook/testing-library": "^0.2.2"
  "@storybook/theming": "^8.6.4"
  "@sveltejs/adapter-auto": "^4.0.0"
  "@sveltejs/kit": "^2.19.0"
  "@sveltejs/vite-plugin-svelte": "^5.0.3"
  "@tailwindcss/postcss": "^4.0.12"
  "@tailwindcss/typography": "^0.5.16"
  "@tailwindcss/vite": "^4.0.12"
  "@tsconfig/svelte": "^5.0.4"
  "@types/google.maps": "^3.58.1"
  "@types/node": "^22.13.10"
  "@types/react-dom": "^19.0.4"
  "@types/react": "^19.0.10"
  "@typescript-eslint/eslint-plugin": "^8.26.0"
  "@typescript-eslint/parser": "^8.26.0"
  vite: "^6.2.1"
  auto: "^11.3.0"
  autoprefixer: "^10.4.20"
  classnames: "^2.5.1"
  commitlint: "^19.8.0"
  eslint-config-prettier: "^10.1.1"
  eslint-plugin-import: "^2.31.0"
  eslint-plugin-jsdoc: "^50.6.3"
  eslint-plugin-svelte: "^3.0.3"
  eslint: "^9.22.0"
  globals: "^16.0.0"
  husky: "^9.1.7"
  lerna: "^8.2.1"
  lint-staged: "^15.4.3"
  mdsvex: "^0.12.3"
  postcss-import: "^16.1.0"
  postcss: "^8.5.3"
  prettier-plugin-svelte: "^3"
  prettier-plugin-tailwindcss: "^0.6.11"
  prettier: "^3.5.3"
  prop-types: "^15.8.1"
  react-dom: "^19.0.0"
  react: "^19.0.0"
  rollup-plugin-svelte: "^7.2.2"
  rollup: "^4.35.0"
  sort-package-json: "^3.0.0"
  storybook: "^8.6.4"
  style-dictionary: "^4.3.3"
  sveld: "^0.22.1"
  svelte-check: "^4.1.5"
  svelte-preprocess: "^6.0.3"
  svelte: "^5.22.6"
  svelte2tsx: "^0.7.35"
  tailwindcss: "^4.0.12"
  tslib: "^2.8.1"
  turbo: "^2.4.4"
  typescript-eslint: "^8.26.0"
  typescript: "^5.8.2"
  yaml: "^2.7.0"
